Db scheme
grigory-pc/java-filmorate pull request #9
Opened 2022-06-10 15:14 UTC by grigory-pc

2022-06-11 06:57 UTC, sergey-oreshkin requested changes
не видны направления связей между таблицами, связи в в основном один ко многим, хотелось бы видеть где один, а где многие.
**таблица friendship_user:**
- отсутствует первичный ключ, если он планируется составной следует выделить все поля которые в него входят.
- user_initiated_friendship - на мой взгляд лишнее поле
- friendship_status значение этого поля сокрее всего бинарно, возможно лучше будет использовать тип boolean
**таблица film_like** - тоже отсутствие первичного ключа
**таблица genre** - не верная связь с фильмами, ведь по условию у одного фильма может быть несколько жанров
**таблица user:**
- плохое название, во многих субд user - зарезервированное слово и такое название может привести к непредсказуемым ошибкам в запросах
- использование естественного первичного ключа в таблице - вопрос дискуссионный, но это оставляю на твое усмотрение

2022-06-11 10:16 UTC, sergey-oreshkin requested changes

2022-06-11 10:16 UTC, sergey-oreshkin commented on README.md
> +GROUP BY fl.film_id
не хватает ограниченя по количеству записей

2022-06-11 10:16 UTC, sergey-oreshkin commented on README.md
> +WHEN u.email LIKE "john@mail.com"
опечатка WHERE а не WHEN

2022-06-11 19:08 UTC, GurevVikrot commented
Привет, sergey-oreshkin в принципе подробно описал все. 

- Чтобы` показать связи таблиц нужно нажать highlight на dbdiagram.io и после этого сохранять картинку. ![image](https://user-images.githubusercontent.com/77064127/173201392-faa8cf88-6d15-47c1-a8b4-5765803e3c56.png)
- Использовать email в качестве первичного ключа не лучшая идея, т.к. пользователь может забыть свой email и поменять его из-за чего придется обновлять все таблицы, где он фигурирует во взаимосвязях. Считаю, что лучше использовать id ведь он не изменяемый.
- Можно добавить ограничение по размерам переменных varchar. Некоторые поля, например названия рейтинга, жанра по логике имеют название максимальной длинны, например какой-нибудь "супер пупер экшн-триллер". Поможет сэкономить размер БД при большом количестве данных.

2022-06-11 20:12 UTC, sergey-oreshkin requested changes
первичный ключ таблицы **film_genre** не соответствует требованию уникальности.
в таблице может быть несколько записей с одним и тем же film_id. лучше сделать составной первичный ключ из обоих полей.
ну и я бы прислушался к товарищу что выше написал про email как первичный ключ.

2022-06-12 11:01 UTC, sergey-oreshkin approved these changes
одобряю )

2022-06-22 08:35 UTC, merged